# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zach Knox
email: hemangsk@gmail.com

#write html inside the double quotes to display in jumbotron
description: "A Computer Science student at George Mason University"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zachknox.me" # the base hostname & protocol for your site
twitter_username: zmknox
github_username:  zmknox

# Build settings
markdown: kramdown
