# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zach Knox

#write html inside the double quotes to display in jumbotron
name: "Zach Knox"
description: "Software developer writing node and cocoa"
url: https://zachknox.com


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zachknox.com" # the base hostname & protocol for your site
twitter_username: zmknox
github_username:  zmknox

# Build settings
markdown: kramdown
